/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginsystem;

//Import classes
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.*; 





/**
 *
 * @author koosh
 */
public class Register extends javax.swing.JFrame {
    
    //Create instances of the user C\lass and the LoginSystem class
    private User user;  
    private LoginSystem login = new LoginSystem(); 

    /**
     * Constructs a new instance of Register. Initializes the components and
     */
    public Register() {
        initComponents();
        // Initialize user object with default values
        this.user = new User("", "","", "", "", "");

    }
     /**
     * This method closes the current panel. It's helpful when we want to switch from one tab to another. 
     */
    public void close() {
        WindowEvent CloseWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(CloseWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        jTextField1.setBackground(new java.awt.Color(153, 204, 255));
        jTextField1.setText("Enter Your Name");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        jTextField2.setText("Enter Your Username");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(153, 204, 255));
        jTextField3.setText("Enter Your Email");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(153, 204, 255));
        jTextField4.setText("Enter Your Age");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(153, 204, 255));
        jTextField5.setText("Enter Your Password");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(153, 204, 255));
        jTextField6.setText("Choose a Code Name");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField5)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
       
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        
    }//GEN-LAST:event_jTextField4ActionPerformed
    /**
     * Handles the action when the user presses Enter in the jTextField2 field.
     * It sets the entered text as the username in the login object.
     *
     * @param evt The ActionEvent instance that triggered the action
     */
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
       login.setUsername(jTextField2.getText());
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        
    }//GEN-LAST:event_jTextField5ActionPerformed
    /**
     * Handles the action when jButton1 is clicked. It reads user input from
     * various text fields and sets them as attributes of the User class. It
     * also checks if the username is already taken and if the password meets
     * the requirements. If the username is available and the password meets the
     * requirements, it writes the user information to a file, closes the
     * current frame, and opens the login menu panel.
     *
     * @param evt The ActionEvent instance that triggered the action
     */

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        
        //Set the doubleUser to false
        login.setDoubleUser(false); 
        
        //Read the user input and update the setters of the User Class with them 
        user.setName(jTextField1.getText());
        
        //Make sure the email is in the correct format
        String email = jTextField3.getText(); 
        
        if (!email.contains("@") || (!email.contains("."))){
            
            //Output to the screen that the email is not correct
            JOptionPane.showMessageDialog(null, "Please enter a valid email address that includes a '@' and a '.'"); 
        }
        
        else {
        user.setEmail(email);
        
        //Store the age into a variabke
        String age = jTextField4.getText(); 
        
        //Convert the age to int
        int ageNum = Integer.parseInt(age); 
        
        //Make sure the age is reasonable 
        if (ageNum > 130){
            JOptionPane.showMessageDialog(null, "There is no way you are older then 130 years old.");
        }
        
        else if (ageNum < 0){
            JOptionPane.showMessageDialog(null, "How are you negative years old? Are you dead?");
        }
        
        else {
        
        //Set the age
        user.setAge(age);
        
        //Pass in the username and password into the LoginSystem class in order to make sure they meet the requirements
        login.setUsername(jTextField2.getText());
        login.setPassword(jTextField5.getText());

        
       //If the username was taken notify the user
        login.userCheck();
        
      if (login.getDoubleUser() == true){
          //Notify the user that the username is taken
            JOptionPane.showMessageDialog(null, "This username is already taken"); 
            
        }
        
       else {
            //Update the username in the User class
            user.setUsername(jTextField2.getText());
         
      }
      
      String codeName = jTextField6.getText(); 
      //Check the code name
      login.codeNameCheck(codeName); 
      //Set the code name if it's valid
      if (login.getInvalidCodeName() == false){
          user.setCodeName(codeName); 
      }
      
        
        //Check to make sure the password meets all the requirements
        login.passCheck(jTextField5.getText());
        
        //Make sure that the password and username inputed meet the requirements and the code name chosen is fine
        if (login.getPassCheck() == true && login.getDoubleUser() == false && login.getInvalidCodeName() == false){
            //pass in the password to the user class
            user.setPass(jTextField5.getText());
            
           
           
            
            //Write all the info to the file
            login.writeFile(user); 
            //Close the current frame
         close();
        //Open the menu panel
        Login n = new Login();
        n.setVisible(true);
        }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Handles the mouse click event when jTextField1 is clicked. It clears the
     * text field jTextField1 when clicked.
     *
     * @param evt The MouseEvent instance that triggered the action
     */
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
       //Set the textfield to empty when clicked 
        jTextField1.setText(""); 
    }//GEN-LAST:event_jTextField1MouseClicked
    /**
     * Handles the mouse click event when jTextField3 is clicked. It clears the
     * text field jTextField1 when clicked.
     *
     * @param evt The MouseEvent instance that triggered the action
     */
    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
       //Set the textfield to empty when clicked 
        jTextField3.setText(""); 
    }//GEN-LAST:event_jTextField3MouseClicked
    /**
     * Handles the mouse click event when jTextField4 is clicked. It clears the
     * text field jTextField1 when clicked.
     *
     * @param evt The MouseEvent instance that triggered the action
     */
    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
      //Set the textfield to empty when clicked 
        jTextField4.setText(""); 
    }//GEN-LAST:event_jTextField4MouseClicked
    /**
     * Handles the mouse click event when jTextField2 is clicked. It clears the
     * text field jTextField1 when clicked.
     *
     * @param evt The MouseEvent instance that triggered the action
     */
    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
      //Set the textfield to empty when clicked 
        jTextField2.setText(""); 
    }//GEN-LAST:event_jTextField2MouseClicked
    /**
     * Handles the mouse click event when jTextField5 is clicked. It clears the
     * text field jTextField1 when clicked.
     *
     * @param evt The MouseEvent instance that triggered the action
     */
    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
       //Set the textfield to empty when clicked 
        jTextField5.setText(""); 
    }//GEN-LAST:event_jTextField5MouseClicked
    /**
     * Handles the action when jButton2 is clicked. It closes the current frame
     * and opens the login menu panel.
     *
     * @param evt The ActionEvent instance that triggered the action
     */

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                //Close the current frame
         close();
        //Open the menu panel
        Login n = new Login();
        n.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
